package cn.cooper.uestc.domain.condition;

import java.util.ArrayList;
import java.util.List;

public class StudentsInformationCondition {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table students_information
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table students_information
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    protected String limit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table students_information
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table students_information
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students_information
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    public StudentsInformationCondition() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students_information
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students_information
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students_information
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    public void setLimit(String limit) {
        this.limit = limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students_information
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    public String getLimit() {
        return limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students_information
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students_information
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students_information
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students_information
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students_information
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students_information
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students_information
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students_information
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table students_information
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andStudentsIdIsNull() {
            addCriterion("students_id is null");
            return (Criteria) this;
        }

        public Criteria andStudentsIdIsNotNull() {
            addCriterion("students_id is not null");
            return (Criteria) this;
        }

        public Criteria andStudentsIdEqualTo(Long value) {
            addCriterion("students_id =", value, "studentsId");
            return (Criteria) this;
        }

        public Criteria andStudentsIdNotEqualTo(Long value) {
            addCriterion("students_id <>", value, "studentsId");
            return (Criteria) this;
        }

        public Criteria andStudentsIdGreaterThan(Long value) {
            addCriterion("students_id >", value, "studentsId");
            return (Criteria) this;
        }

        public Criteria andStudentsIdGreaterThanOrEqualTo(Long value) {
            addCriterion("students_id >=", value, "studentsId");
            return (Criteria) this;
        }

        public Criteria andStudentsIdLessThan(Long value) {
            addCriterion("students_id <", value, "studentsId");
            return (Criteria) this;
        }

        public Criteria andStudentsIdLessThanOrEqualTo(Long value) {
            addCriterion("students_id <=", value, "studentsId");
            return (Criteria) this;
        }

        public Criteria andStudentsIdIn(List<Long> values) {
            addCriterion("students_id in", values, "studentsId");
            return (Criteria) this;
        }

        public Criteria andStudentsIdNotIn(List<Long> values) {
            addCriterion("students_id not in", values, "studentsId");
            return (Criteria) this;
        }

        public Criteria andStudentsIdBetween(Long value1, Long value2) {
            addCriterion("students_id between", value1, value2, "studentsId");
            return (Criteria) this;
        }

        public Criteria andStudentsIdNotBetween(Long value1, Long value2) {
            addCriterion("students_id not between", value1, value2, "studentsId");
            return (Criteria) this;
        }

        public Criteria andStudentsNameIsNull() {
            addCriterion("students_name is null");
            return (Criteria) this;
        }

        public Criteria andStudentsNameIsNotNull() {
            addCriterion("students_name is not null");
            return (Criteria) this;
        }

        public Criteria andStudentsNameEqualTo(String value) {
            addCriterion("students_name =", value, "studentsName");
            return (Criteria) this;
        }

        public Criteria andStudentsNameNotEqualTo(String value) {
            addCriterion("students_name <>", value, "studentsName");
            return (Criteria) this;
        }

        public Criteria andStudentsNameGreaterThan(String value) {
            addCriterion("students_name >", value, "studentsName");
            return (Criteria) this;
        }

        public Criteria andStudentsNameGreaterThanOrEqualTo(String value) {
            addCriterion("students_name >=", value, "studentsName");
            return (Criteria) this;
        }

        public Criteria andStudentsNameLessThan(String value) {
            addCriterion("students_name <", value, "studentsName");
            return (Criteria) this;
        }

        public Criteria andStudentsNameLessThanOrEqualTo(String value) {
            addCriterion("students_name <=", value, "studentsName");
            return (Criteria) this;
        }

        public Criteria andStudentsNameLike(String value) {
            addCriterion("students_name like", value, "studentsName");
            return (Criteria) this;
        }

        public Criteria andStudentsNameNotLike(String value) {
            addCriterion("students_name not like", value, "studentsName");
            return (Criteria) this;
        }

        public Criteria andStudentsNameIn(List<String> values) {
            addCriterion("students_name in", values, "studentsName");
            return (Criteria) this;
        }

        public Criteria andStudentsNameNotIn(List<String> values) {
            addCriterion("students_name not in", values, "studentsName");
            return (Criteria) this;
        }

        public Criteria andStudentsNameBetween(String value1, String value2) {
            addCriterion("students_name between", value1, value2, "studentsName");
            return (Criteria) this;
        }

        public Criteria andStudentsNameNotBetween(String value1, String value2) {
            addCriterion("students_name not between", value1, value2, "studentsName");
            return (Criteria) this;
        }

        public Criteria andInstituteIsNull() {
            addCriterion("institute is null");
            return (Criteria) this;
        }

        public Criteria andInstituteIsNotNull() {
            addCriterion("institute is not null");
            return (Criteria) this;
        }

        public Criteria andInstituteEqualTo(String value) {
            addCriterion("institute =", value, "institute");
            return (Criteria) this;
        }

        public Criteria andInstituteNotEqualTo(String value) {
            addCriterion("institute <>", value, "institute");
            return (Criteria) this;
        }

        public Criteria andInstituteGreaterThan(String value) {
            addCriterion("institute >", value, "institute");
            return (Criteria) this;
        }

        public Criteria andInstituteGreaterThanOrEqualTo(String value) {
            addCriterion("institute >=", value, "institute");
            return (Criteria) this;
        }

        public Criteria andInstituteLessThan(String value) {
            addCriterion("institute <", value, "institute");
            return (Criteria) this;
        }

        public Criteria andInstituteLessThanOrEqualTo(String value) {
            addCriterion("institute <=", value, "institute");
            return (Criteria) this;
        }

        public Criteria andInstituteLike(String value) {
            addCriterion("institute like", value, "institute");
            return (Criteria) this;
        }

        public Criteria andInstituteNotLike(String value) {
            addCriterion("institute not like", value, "institute");
            return (Criteria) this;
        }

        public Criteria andInstituteIn(List<String> values) {
            addCriterion("institute in", values, "institute");
            return (Criteria) this;
        }

        public Criteria andInstituteNotIn(List<String> values) {
            addCriterion("institute not in", values, "institute");
            return (Criteria) this;
        }

        public Criteria andInstituteBetween(String value1, String value2) {
            addCriterion("institute between", value1, value2, "institute");
            return (Criteria) this;
        }

        public Criteria andInstituteNotBetween(String value1, String value2) {
            addCriterion("institute not between", value1, value2, "institute");
            return (Criteria) this;
        }

        public Criteria andBorrowStatusIsNull() {
            addCriterion("borrow_status is null");
            return (Criteria) this;
        }

        public Criteria andBorrowStatusIsNotNull() {
            addCriterion("borrow_status is not null");
            return (Criteria) this;
        }

        public Criteria andBorrowStatusEqualTo(String value) {
            addCriterion("borrow_status =", value, "borrowStatus");
            return (Criteria) this;
        }

        public Criteria andBorrowStatusNotEqualTo(String value) {
            addCriterion("borrow_status <>", value, "borrowStatus");
            return (Criteria) this;
        }

        public Criteria andBorrowStatusGreaterThan(String value) {
            addCriterion("borrow_status >", value, "borrowStatus");
            return (Criteria) this;
        }

        public Criteria andBorrowStatusGreaterThanOrEqualTo(String value) {
            addCriterion("borrow_status >=", value, "borrowStatus");
            return (Criteria) this;
        }

        public Criteria andBorrowStatusLessThan(String value) {
            addCriterion("borrow_status <", value, "borrowStatus");
            return (Criteria) this;
        }

        public Criteria andBorrowStatusLessThanOrEqualTo(String value) {
            addCriterion("borrow_status <=", value, "borrowStatus");
            return (Criteria) this;
        }

        public Criteria andBorrowStatusLike(String value) {
            addCriterion("borrow_status like", value, "borrowStatus");
            return (Criteria) this;
        }

        public Criteria andBorrowStatusNotLike(String value) {
            addCriterion("borrow_status not like", value, "borrowStatus");
            return (Criteria) this;
        }

        public Criteria andBorrowStatusIn(List<String> values) {
            addCriterion("borrow_status in", values, "borrowStatus");
            return (Criteria) this;
        }

        public Criteria andBorrowStatusNotIn(List<String> values) {
            addCriterion("borrow_status not in", values, "borrowStatus");
            return (Criteria) this;
        }

        public Criteria andBorrowStatusBetween(String value1, String value2) {
            addCriterion("borrow_status between", value1, value2, "borrowStatus");
            return (Criteria) this;
        }

        public Criteria andBorrowStatusNotBetween(String value1, String value2) {
            addCriterion("borrow_status not between", value1, value2, "borrowStatus");
            return (Criteria) this;
        }

        public Criteria andLimitbooksIsNull() {
            addCriterion("LimitBooks is null");
            return (Criteria) this;
        }

        public Criteria andLimitbooksIsNotNull() {
            addCriterion("LimitBooks is not null");
            return (Criteria) this;
        }

        public Criteria andLimitbooksEqualTo(Integer value) {
            addCriterion("LimitBooks =", value, "limitbooks");
            return (Criteria) this;
        }

        public Criteria andLimitbooksNotEqualTo(Integer value) {
            addCriterion("LimitBooks <>", value, "limitbooks");
            return (Criteria) this;
        }

        public Criteria andLimitbooksGreaterThan(Integer value) {
            addCriterion("LimitBooks >", value, "limitbooks");
            return (Criteria) this;
        }

        public Criteria andLimitbooksGreaterThanOrEqualTo(Integer value) {
            addCriterion("LimitBooks >=", value, "limitbooks");
            return (Criteria) this;
        }

        public Criteria andLimitbooksLessThan(Integer value) {
            addCriterion("LimitBooks <", value, "limitbooks");
            return (Criteria) this;
        }

        public Criteria andLimitbooksLessThanOrEqualTo(Integer value) {
            addCriterion("LimitBooks <=", value, "limitbooks");
            return (Criteria) this;
        }

        public Criteria andLimitbooksIn(List<Integer> values) {
            addCriterion("LimitBooks in", values, "limitbooks");
            return (Criteria) this;
        }

        public Criteria andLimitbooksNotIn(List<Integer> values) {
            addCriterion("LimitBooks not in", values, "limitbooks");
            return (Criteria) this;
        }

        public Criteria andLimitbooksBetween(Integer value1, Integer value2) {
            addCriterion("LimitBooks between", value1, value2, "limitbooks");
            return (Criteria) this;
        }

        public Criteria andLimitbooksNotBetween(Integer value1, Integer value2) {
            addCriterion("LimitBooks not between", value1, value2, "limitbooks");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table students_information
     *
     * @mbggenerated do_not_delete_during_merge Sun Mar 18 00:39:17 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table students_information
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}