package cn.cooper.uestc.mapper;

import cn.cooper.uestc.domain.BorrowingTableDo;
import cn.cooper.uestc.domain.condition.BorrowingTableCondition;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BorrowingTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrowing_table
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    int countByExample(BorrowingTableCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrowing_table
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    int deleteByExample(BorrowingTableCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrowing_table
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrowing_table
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    int insert(BorrowingTableDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrowing_table
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    int insertSelective(BorrowingTableDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrowing_table
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    List<BorrowingTableDo> selectByExample(BorrowingTableCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrowing_table
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    BorrowingTableDo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrowing_table
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    int updateByExampleSelective(@Param("record") BorrowingTableDo record, @Param("example") BorrowingTableCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrowing_table
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    int updateByExample(@Param("record") BorrowingTableDo record, @Param("example") BorrowingTableCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrowing_table
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    int updateByPrimaryKeySelective(BorrowingTableDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrowing_table
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    int updateByPrimaryKey(BorrowingTableDo record);
}