package cn.cooper.uestc.mapper;

import cn.cooper.uestc.domain.PasswordTableDo;
import cn.cooper.uestc.domain.condition.PasswordTableCondition;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PasswordTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password_table
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    int countByExample(PasswordTableCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password_table
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    int deleteByExample(PasswordTableCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password_table
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password_table
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    int insert(PasswordTableDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password_table
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    int insertSelective(PasswordTableDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password_table
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    List<PasswordTableDo> selectByExample(PasswordTableCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password_table
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    PasswordTableDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password_table
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    int updateByExampleSelective(@Param("record") PasswordTableDo record, @Param("example") PasswordTableCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password_table
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    int updateByExample(@Param("record") PasswordTableDo record, @Param("example") PasswordTableCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password_table
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    int updateByPrimaryKeySelective(PasswordTableDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password_table
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    int updateByPrimaryKey(PasswordTableDo record);
}