package cn.cooper.uestc.mapper;

import cn.cooper.uestc.domain.RepositoryTableDo;
import cn.cooper.uestc.domain.condition.RepositoryTableCondition;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RepositoryTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Repository_table
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    int countByExample(RepositoryTableCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Repository_table
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    int deleteByExample(RepositoryTableCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Repository_table
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Repository_table
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    int insert(RepositoryTableDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Repository_table
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    int insertSelective(RepositoryTableDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Repository_table
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    List<RepositoryTableDo> selectByExample(RepositoryTableCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Repository_table
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    RepositoryTableDo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Repository_table
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    int updateByExampleSelective(@Param("record") RepositoryTableDo record, @Param("example") RepositoryTableCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Repository_table
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    int updateByExample(@Param("record") RepositoryTableDo record, @Param("example") RepositoryTableCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Repository_table
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    int updateByPrimaryKeySelective(RepositoryTableDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Repository_table
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    int updateByPrimaryKey(RepositoryTableDo record);
}