package cn.cooper.uestc.mapper;

import cn.cooper.uestc.domain.StudentsInformationDo;
import cn.cooper.uestc.domain.condition.StudentsInformationCondition;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudentsInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students_information
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    int countByExample(StudentsInformationCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students_information
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    int deleteByExample(StudentsInformationCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students_information
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students_information
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    int insert(StudentsInformationDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students_information
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    int insertSelective(StudentsInformationDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students_information
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    List<StudentsInformationDo> selectByExample(StudentsInformationCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students_information
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    StudentsInformationDo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students_information
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    int updateByExampleSelective(@Param("record") StudentsInformationDo record, @Param("example") StudentsInformationCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students_information
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    int updateByExample(@Param("record") StudentsInformationDo record, @Param("example") StudentsInformationCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students_information
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    int updateByPrimaryKeySelective(StudentsInformationDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students_information
     *
     * @mbggenerated Sun Mar 18 00:39:17 CST 2018
     */
    int updateByPrimaryKey(StudentsInformationDo record);
}